# Generated by Django 4.2.10 on 2024-08-25 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccinationCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('working_hours', models.CharField(max_length=100)),
                ('total_slots_per_day', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='VaccinationSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('slot_time', models.CharField(choices=[('09:00', '09:00 AM - 10:00 AM'), ('10:00', '10:00 AM - 11:00 AM'), ('11:00', '11:00 AM - 12:00 PM'), ('12:00', '12:00 PM - 01:00 PM'), ('01:00', '01:00 PM - 02:00 PM'), ('02:00', '02:00 PM - 03:00 PM'), ('03:00', '03:00 PM - 04:00 PM'), ('04:00', '04:00 PM - 05:00 PM')], max_length=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vaccination_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking_app.vaccinationcenter')),
            ],
            options={
                'unique_together': {('vaccination_center', 'date', 'slot_time')},
            },
        ),
    ]
