# Generated by Django 4.2.10 on 2024-08-25 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinationcenter',
            name='total_dosage_given',
            field=models.IntegerField(default=0),
        ),
    ]
