# Generated by Django 4.2.10 on 2024-08-25 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0002_vaccinationcenter_total_dosage_given'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinationslot',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed')], default='pending', max_length=10),
        ),
    ]
